Luxer:
  every: 300m
  class: Luxer
  args: 
  description:
QQ_Mover:
  cron: "0 8 * * *"
  class: MV_QQ
  args:  
Sohu_Mover:
  cron: "0 8 * * *"
  class: MV_Sohu
  args: 
Other_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "other" 
Yahoo_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "yahoo" 
Tom_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "tom" 
Gmail_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "gmail" 
Hotmail_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "hotmail" 
163_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "163" 
Sina_Mover:
  cron: "0 8 * * *"
  class: MV_Worker
  args: "sina" 
