default: &default
  website:
    title: FocusMail代理
    favicon: ./images/favicon.gif
  thread:
    wget: agent_wget.rb
    mv2wait: agent_mv2wait.rb
  mailgates: 
    speed: 300
    wait_path: /Users/lijunjie/Code/work/focus_mail_agent/public/wait
    log_file: /mailgates/mqueue/log/mgmailerd.log
    archive_log_path: /mailgates/mqueue/archived

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: ''
