default: &default
  website:
    title: FocusMail代理
    favicon: ./images/favicon.gif
  thread:
    wget: agent_wget.rb
    mv2wait: agent_mv2wait.rb
  mailgates: 
    speed: 300
    wait_path: /mailgates/mqueue/wait/
    log_file: /mailgates/mqueue/log/mgmailerd.log
    log_archive_path: /mailgates/log_archive/

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: ''
